### ISSUE TITLE
radial-progress-bar

### ISSUE THREAD

**Issue by jinjinwa** [wyzant-dev/vue-radial-progress#2]
使用多个radial-progress-bar，每个不能够单独配置，配置第二个的颜色，会覆盖第一个

**Comment by jrenton** [comment]
Ah you are right, thank you. I thought I had fixed this before

**Comment by jrenton** [comment]
Ok this should be fixed in `0.2.10`

**Comment by jinjinwa** [comment]
thank you

**Comment by Cholowao** [comment]
what, what he said
